name: Add TGS Version

on:
  workflow_dispatch:
    inputs:
      tgs_semver:
        description: 'TGS Version'
        required: true
        type: string

concurrency:
  group: "package-update-${{ github.head_ref || github.run_id }}-${{ github.event_name }}"
  cancel-in-progress: false

jobs:
  add_tgs_version:
    name: Add TGS Version
    runs-on: ubuntu-latest
    steps:
    - name: apt-get update
      run: sudo apt-get update

    - name: Install Tools
      run: sudo apt-get install -y git curl reprepro gnupg2 procps

    - name: Initialize gpg-agent
      run: |
        gpg --list-keys # Needed to initialize gpg home dir if it isn't
        echo batch > $HOME/.gnupg/gpg-agent.conf
        gpg-connect-agent reloadagent /bye

    - name: Import GPG Key
      run: |
        echo "${{ secrets.REPO_PRIVATE_KEY }}" > private.pgp
        echo ${{ secrets.REPO_PRIVATE_KEY_PASSPHRASE }} | gpg --batch --yes --passphrase-fd 0 --import private.pgp
        rm private.pgp

    - name: Clone gh-pages
      run: git clone -b gh-pages --single-branch "https://git@github.com/tgstation/tgstation-ppa" $HOME/ppa

    - name: Download TGS amd64 .deb
      run: curl -L https://github.com/tgstation/tgstation-server/releases/download/tgstation-server-v${{ github.event.inputs.tgs_semver }}/tgstation-server_5.12.6-1_amd64.deb -o $HOME/tgstation-server_5.12.6-1_amd64.deb

    - name: Download TGS .dsc
      run: curl -L https://github.com/tgstation/tgstation-server/releases/download/tgstation-server-v${{ github.event.inputs.tgs_semver }}/tgstation-server_5.12.6-1.dsc -o $HOME/tgstation-server_5.12.6-1.dsc

    - name: Run includedeb
      run: |
        cd $HOME/ppa/debian
        reprepro includedeb unstable $HOME/tgstation-server_5.12.6-1_amd64.deb

    - name: Run includedsc
      run: |
        cd $HOME/ppa/debian
        reprepro includedsc unstable $HOME/tgstation-server_5.12.6-1.dsc

    - name: Commit
      run: |
        cd $HOME/ppa
        git config user.name "tgstation-server"
        git config user.email "tgstation-server@tgstation13.org"
        echo '# THIS BRANCH IS AUTO GENERATED BY GITHUB ACTIONS' > README.md
        git add --all
        git diff-index --quiet HEAD || git commit -m "Update repository for workflow run ${{ github.run_number }}" -m "TGS Version: ${{ github.event.inputs.tgs_semver }}"

    - name: Push
      run: |
        cd $HOME/ppa
        git push "https://${{ secrets.GH_PAGES_PUSH_TOKEN }}@github.com/tgstation/tgstation-ppa"
